### PR TITLE
PLS-3237 - fix add V2.1 student fields

### PR DESCRIPTION
**Pull request by yratanov**

### CODE REVIEW

**Comment by pikislabis** [comment]
@yratanov you need to commit changes made into Gemfile.lock.

**Comment by yratanov** [comment]
@pikislabis you mean in pulse-app?

**Comment by yratanov** [comment]
@pikislabis @drosam can you take a look please?

**Review by drosam — APPROVED** [review]

**Comment by pikislabis** [comment]
> @pikislabis you mean in pulse-app?

I mean here @yratanov

**Comment by pikislabis** [comment]
@yratanov 
https://github.com/mysencare/clever-ruby/blob/c0e5f6ac5a50d93a782d70641b41d4fa6abfe8fe/Gemfile.lock#L4

We need to put here 2.1.0

**Comment by yratanov** [comment]
@pikislabis done!

**Review by pikislabis — APPROVED** [review]
LGTM! 💪

**Pull request merged**
